name: peyote
favicon: null
layout_spectrum: 0.1977958839852363
typography_spectrum: 0.16583189787343144
title: peyote
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aacc4d'
    - '#304632'
    - '#c4404e'
    - '#ffffff'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
